name = "NeuralNetsLux"
uuid = "3eb6d2f4-7bd6-458c-954e-c6012ef3e24a"
authors = ["AndiMD <none@gmx.net> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
